export const PLAYER_LIST_REQUEST = 'PLAYER_LIST_REQUEST'
export const PLAYER_LIST_SUCCESS = 'PLAYER_LIST_SUCCESS'
export const PLAYER_LIST_FAIL = 'PLAYER_LIST_FAIL'

export const PLAYER_DETAIL_REQUEST = 'PLAYER_DETAIL_REQUEST'
export const PLAYER_DETAIL_SUCCESS = 'PLAYER_DETAIL_SUCCESS'
export const PLAYER_DETAIL_FAIL = 'PLAYER_DETAIL_FAIL'